name: DisciplineX
version: '1.0-SNAPSHOT'
main: xyz.nameredacted.disciplinex.DisciplineX
author: 928533G
api-version: '1.21'

commands:
  kick:
    description: Kick a player
    usage: /kick <player>
#    permission: disciplinex.moderation.ban
  ban:
    description: Ban a player for an infinite or finite amount of time.
#    permission: disciplinex.moderation.ban
  mute:
#    permission: disciplinex.moderation.mute
  warn:
#    permission: disciplinex.moderation.warn
